---
title: "Atividade 11"
author: "Gabriel Ozélo Braga - RA:247345"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(gapminder)
library(agridat)
```

# 1.
### a.
```{r, echo=FALSE}
grafico <- cars %>% ggplot() + geom_point(aes(x = speed, y = dist, color = "red")) + labs(title = "Dados de 1920", x = "Velocidade", y = "Distancia")
grafico
```

### b.
```{r, echo=FALSE}
grafico <- cars %>% ggplot() + geom_point(aes(x = speed, y = dist, color = speed)) + labs(title = "Dados de 1920", x = "Velocidade", y = "Distancia") + scale_color_gradient(low = "black", high = "red")
grafico
```

### c.
```{r, echo=FALSE}
grafico <- cars %>% ggplot() + geom_point(aes(x = speed, y = dist, color = dist+speed)) + labs(title = "Dados de 1920", x = "Velocidade", y = "Distancia") + scale_color_gradient(low = "blue", high = "red")
grafico
```

### d.
```{r, echo=FALSE}
grafico <- cars %>% ggplot() + geom_point(aes(x = speed, y = dist, color = dist+speed)) + labs(title = "Dados de 1920", x = "Velocidade", y = "Distancia") + scale_color_gradient(low = "blue", high = "red") + geom_smooth(aes(x = speed, y = dist), method = "lm", se = FALSE)
grafico
```

# 2.

# 3.
## a.
```{r, echo=FALSE}
iris_box <- ggplot(iris) + geom_boxplot(aes(x = Species, y = Sepal.Width, fill = Species)) + labs(title = "Comprimento da Sepala por especie", x = "Especie", y = "Comprimento")
iris_box
```

## b.
```{r, echo=FALSE}
iris_box <- ggplot(iris) + geom_boxplot(aes(x = Sepal.Width, y = Species, fill = Species)) + labs(title = "Comprimento da Sepala por especie", x = "Especie", y = "Comprimento")
iris_box
```

# 4.
## a.
```{r, echo=FALSE}
hist <- goulden.barley.uniformity %>% ggplot() + geom_histogram(aes(x = yield), color = 1, fill = 5, binwidth = 19.5) + labs(title = "Producao de cevada")
hist
```
## b.
```{r, echo=FALSE}
hist <- goulden.barley.uniformity %>% ggplot(aes(x = yield, y = after_stat(density))) + geom_histogram(color = 1, fill = 5, binwidth = 19.5) + labs(title = "Producao de cevada") + geom_density(stat = "density", alpha = 0.2)
hist
```
